config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :notes, only: [:index, :show, :update, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  serialize :body

  def to_param() = date

  def checklist_items(sigils: {
    todos: ENV.fetch("SIGIL_TODO") { "=" },
    dones: ENV.fetch("SIGIL_DONE") { "~" },
    crits: ENV.fetch("SIGIL_CRIT") { "!" },
  })
    ret_val = {
      todos: [],
      dones: [],
      crits: [],
    }
    return ret_val unless persisted?

    Rails.cache.fetch([self, :checklist_items]) do
      body
        .each_line
        .map.with_index { |line, number|
          sigils.each do |key, sigil|
            next unless line.start_with? "#{sigil} "
            ret_val.fetch(key).push({
              line: line.chomp.gsub(sigil, ""),
              number: number + 1
            })
          end
        }
        .compact

      puts ret_val.inspect
      ret_val
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.where(date: (Date.today.beginning_of_month...Date.today.end_of_month).map(&:to_s))
  end

  def show
    @note = Note.where(date: params[:id]).first || Note.new(date: params[:id])
  end

  def create() = update

  def update
    @note = Note.where(date: params[:id]).first || Note.new(note_params)

    if @note.persisted?
      if @note.update(note_params)
        redirect_to @note
      else
        render :show, status: :unprocessable_entity
      end
    else
      if @note.save
        redirect_to @note
      else
        render :show, status: :unprocessable_entity
      end
    end
  end

  private
  def note_params
    params.require(:note).permit(:date, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def has_notes_class(date) = Note.where(date: date).exists? ? "font-bold" : nil
  def today_class(date) = Date.today == date ? "text-red-500" : nil
  def current_date_class(date, start_date) = date == start_date ? "bg-amber-200" : nil
  def hover_class(date, start_date) = date != start_date ? "hover:bg-sky-300" : nil

  def prev_month_class(date, start_date)
    (start_date.month != date.month && date < start_date) ? "bg-gray-200" : nil
  end

  def next_month_class(date, start_date)
    (start_date.month != date.month && date > start_date) ? "bg-gray-200" : nil
  end

  def date_classes(date, start_date_param)
    start_date = Date.parse(start_date_param)
    <<~CLASSES
      #{today_class(date)}
      #{has_notes_class(date)}
      #{next_month_class(date, start_date)}
      #{prev_month_class(date, start_date)}
      #{current_date_class(date, start_date)}
      #{hover_class(date, start_date)}
    CLASSES
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NittyPages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mt-5 px-5 w-full">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_calendar.html.erb
<%= month_calendar(start_date_param: :id) do |date| %>
  <%= link_to note_path(date), data: { turbo_frame: '_top' } do %>
    <div class="
      <%= date_classes(date, params[:id]) %>
      lg:h-8 xl:h-12 2xl:h-16 w-full min-w-max
      border border-gray-300
      table
      text-sm lg:text-base
    ">
      <span class="table-cell align-middle text-center">
        <%= date.mday %>
      </span>
    </div>
  <% end %>
<% end %>

app/views/notes/_checklist.html.erb
<ul class="whitespace-normal w-full list-[square] px-4">
  <% note.checklist_items.fetch(:crits).each do |todo| %>
    <li class="font-bold"><%= todo.fetch(:line) %> [<%= todo.fetch(:number) %>]</li>
  <% end %>
</ul>

<ul class="whitespace-normal w-full list-[square] px-4">
  <% note.checklist_items.fetch(:todos).each do |todo| %>
    <li class=""><%= todo.fetch(:line) %> [<%= todo.fetch(:number) %>]</li>
  <% end %>
</ul>


<% if note.checklist_items.fetch(:dones).count > 0 %>
  <details class="cursor-pointer">
    <summary>Done Items</summary>
    <ul class="whitespace-normal w-full list-[square] px-4 mx-5">
      <% note.checklist_items.fetch(:dones).each do |todo| %>
        <li class="line-through"><%= todo.fetch(:line) %> [<%= todo.fetch(:number) %>]</li>
      <% end %>
    </ul>
  </details>
<% end %>

app/views/notes/_form.html.erb
<%= form_with model: @note, html: { class: "w-full h-full" } do |form| %>
  <div class="w-full h-full">
    <%= form.text_area :body, class: 'w-full h-full' %>
  </div>

  <%= form.hidden_field :date %>

  <div class="py-2" >
    <%= form.submit nil, class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2" %>
    <% if @note.persisted? %>
      <span>Last saved: <%= time_ago_in_words @note.updated_at %> ago.
    <% end %>
  </div>
<% end %>

app/views/notes/index.html.erb
<div class="py-2">
<% @notes.reverse.each do |note| %>
  <div class="py-2">
    <%= link_to note_path(note) do %>
      <span class="underline text-blue-600">
        <%= note.date %>
      </span>
    <% end %>
    <%= render "checklist", note: note %>
  </div>
<% end %>
</div>

<%= link_to "Today", note_path(Date.today.to_s), class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2" %>

app/views/notes/show.html.erb
<div class="grid grid-cols-4 gap-4 h-[90vh]">
  <div class="lg:block lg:col-span-1 lg:min-w-max hidden">
    <div class="py-2">
      <%= turbo_frame_tag 'calendar' do %>
        <% cache @note do %>
          <%= render "calendar", note: @note%>
        <% end %>
      <% end %>
    </div>

    <hr />

    <div class="py-2 w-80 lg:w-64 xl:w-96">
      <%= render "checklist", note: @note %>
    </div>

    <%= link_to "This month's notes", notes_path, class: "cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mx-2" %>

  </div>

  <div class="lg:h-full lg:col-start-2 col-start-1 col-span-4">
    <%= render "form", note: @note %>
  </div>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="grid grid-cols-7">
    <% date_range.slice(0, 7).each do |day| %>
      <div class="text-center"><%= t('date.abbr_day_names')[day.wday] %></div>
    <% end %>

    <% date_range.each_slice(7) do |week| %>
      <% week.each do |day| %>
        <%= content_tag :div, class: calendar.td_classes_for(day) do %>
          <% passed_block.call day, sorted_events.fetch(day, []) %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="calendar-heading grid grid-cols-2">
    <div>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view, data: { turbo_frame: '_top' } %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </div>
    <span class="calendar-title text-right"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
  </div>

</div>